### PR TITLE
Remove required = true from Jackson property annotation

### LINKED ISSUE #2169: Do not set required = true in @JsonProperty for deserialization of properties
When deserializing a service response, we should not fail if a required property is not included in the response. This is a use case for OpenAI where the streaming response will not have some fields that are otherwise required for non-streaming responses.

### PR DESCRIPTION
**Pull request by srnagar**
Fixes #2169

### CODE REVIEW

File: typespec-tests/src/main/java/com/_specs_/azure/clientgenerator/core/internal/models/PublicModel.java [hunk 1]
```diff
@@ -16,7 +16,7 @@ public final class PublicModel {
      * The name property.
      */
     @Generated
-    @JsonProperty(value = "name", required = true)
+    @JsonProperty(value = "name")
```
Comment (weidongxu-microsoft) [inline typespec-tests/src/main/java/com/_specs_/azure/clientgenerator/core/internal/models/PublicModel.java:19]: Technically we only need to remove the `required=true` in ctor. But I guess it is also fine here.

**Review by weidongxu-microsoft — APPROVED** [review]

**Review by weidongxu-microsoft — APPROVED** [review]
