### PR TITLE
Fix constants and parameter names

### LINKED ISSUE #407: Add constant support in `IType`
Today there's no constant support in IType - when we reference a constant type, we actually just use the backing type, e.g. String, int, etc, thus missing the constant value.

### PR DESCRIPTION
**Pull request by srnagar**
Fixes #407

### CODE REVIEW

File: tests/src/main/java/fixtures/header/models/HeadersResponseEnumHeaders.java [hunk 1]
```diff
@@ -12,14 +12,14 @@
      * The value property.
      */
     @JsonProperty(value = "value")
-    private GreyscaleColors value;
+    private Enum0 value;
```
Comment (weidongxu-microsoft) [inline tests/src/main/java/fixtures/header/models/HeadersResponseEnumHeaders.java]: This might be a autorest.core issue.

Yesterday I updated to latest autorest-beta and autorest.core, regenerate header.json with our latest java v4. And this enum is  `GreyscaleColors` (I think this should be the correct class, not Enum0), and `Enum0.java` is not generated.
